### ISSUE TITLE
Focused is not working

### ISSUE THREAD

**Issue by dudu1533** [giansalex/MaterialSkin#1]
Focused object on a textbox is not working, even the control is focused.
Always returning false.

**Comment by giansalex** [comment]
Are you using `GotFocus` event?

**Comment by dudu1533** [comment]
Hi,


No, i'm not using.

I'm just using element.Focus().

**Comment by giansalex** [comment]
I tried with `MaterialSingleLineTextField`,  it's working.
from where you call `element.Focus()`

**Comment by dudu1533** [comment]
Right..
After you use element.Focus(), please, check if element.Focused = true.

**Comment by giansalex** [comment]
Yes, you are right.
I suggest use 
https://www.nuget.org/packages/MaterialSkin.Updated/

**Comment by dudu1533** [comment]
I installed this package and unistalled the MaterialSkin .NET4.
Is it ok?

**Comment by dudu1533** [comment]
When i'm trying using MaterialSkin.Updated, after trying compile, shows the error:

**The type or namespace name 'MaterialSkin' could not be found (are you missing a using directive or an assembly reference?)**

But the assembly is registered in References

**Comment by giansalex** [comment]
Required .NET Framework v4.6.1

**Comment by ttodua** [comment]
and could it be fixed for #4.5 , if we dont user MaterialSkin.Updated package?
